//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentEmployee
    {
        public int StudentEmployeeID { get; set; }
        public int StudentID { get; set; }
        public int EmployeeID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Student Student { get; set; }
    }
}
